"""add usage logs and query cost fields

Revision ID: 5014feae18a0
Revises: 7ef828df7158
Create Date: 2026-06-16 16:46:46.335031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5014feae18a0'
down_revision: Union[str, Sequence[str], None] = '7ef828df7158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('api_key_id', sa.String(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_api_key_id'), 'api_usage_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_id'), 'api_usage_logs', ['id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_project_id'), 'api_usage_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_request_id'), 'api_usage_logs', ['request_id'], unique=False)
    op.add_column(
        'query_logs',
        sa.Column(
            'estimated_tokens',
            sa.Integer(),
            nullable=False,
            server_default='0'
        )
    )

    op.add_column(
        'query_logs',
        sa.Column(
            'estimated_cost',
            sa.Float(),
            nullable=False,
            server_default='0.0'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'estimated_cost')
    op.drop_column('query_logs', 'estimated_tokens')
    op.drop_index(op.f('ix_api_usage_logs_request_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_project_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_api_key_id'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
