"""add_version_5_enterprise_tables

Revision ID: abab33d1946e
Revises: 5014feae18a0
Create Date: 2026-06-17 12:22:39.110157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abab33d1946e'
down_revision: Union[str, Sequence[str], None] = '5014feae18a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('api_key_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_provider_configs_id'), 'llm_provider_configs', ['id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_memberships_id'), 'project_memberships', ['id'], unique=False)
    op.create_table('widget_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('primary_color', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('allowed_domains', sa.JSON(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('widget_public_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_widget_configs_id'), 'widget_configs', ['id'], unique=False)
    op.create_index(op.f('ix_widget_configs_widget_public_key'), 'widget_configs', ['widget_public_key'], unique=True)
    op.add_column('client_api_keys', sa.Column('key_hash', sa.String(length=255), nullable=True))
    op.add_column('client_api_keys', sa.Column('key_preview', sa.String(length=50), nullable=True))
    op.add_column('client_api_keys', sa.Column('key_type', sa.String(length=50), nullable=True))
    op.add_column('client_api_keys', sa.Column('scopes', sa.JSON(), nullable=True))
    op.add_column('client_api_keys', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('company_name', sa.String(length=150), nullable=True))
    op.add_column('clients', sa.Column('plan', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('project_api_keys', sa.Column('key_hash', sa.String(length=255), nullable=True))
    op.add_column('project_api_keys', sa.Column('key_preview', sa.String(length=50), nullable=True))
    op.add_column('project_api_keys', sa.Column('key_type', sa.String(length=50), nullable=True))
    op.add_column('project_api_keys', sa.Column('scopes', sa.JSON(), nullable=True))
    op.add_column('project_api_keys', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('visibility', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('default_llm_provider', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('default_model_name', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('widget_enabled', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('widget_public_key', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_projects_widget_public_key'), 'projects', ['widget_public_key'], unique=True)
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_widget_public_key'), table_name='projects')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'widget_public_key')
    op.drop_column('projects', 'widget_enabled')
    op.drop_column('projects', 'default_model_name')
    op.drop_column('projects', 'default_llm_provider')
    op.drop_column('projects', 'visibility')
    op.drop_column('project_api_keys', 'last_used_at')
    op.drop_column('project_api_keys', 'scopes')
    op.drop_column('project_api_keys', 'key_type')
    op.drop_column('project_api_keys', 'key_preview')
    op.drop_column('project_api_keys', 'key_hash')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'status')
    op.drop_column('clients', 'plan')
    op.drop_column('clients', 'company_name')
    op.drop_column('client_api_keys', 'last_used_at')
    op.drop_column('client_api_keys', 'scopes')
    op.drop_column('client_api_keys', 'key_type')
    op.drop_column('client_api_keys', 'key_preview')
    op.drop_column('client_api_keys', 'key_hash')
    op.drop_index(op.f('ix_widget_configs_widget_public_key'), table_name='widget_configs')
    op.drop_index(op.f('ix_widget_configs_id'), table_name='widget_configs')
    op.drop_table('widget_configs')
    op.drop_index(op.f('ix_project_memberships_id'), table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_index(op.f('ix_llm_provider_configs_id'), table_name='llm_provider_configs')
    op.drop_table('llm_provider_configs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
